name: Publish to Maven Repository
on:
  release:
    types: [published]

jobs:
  publish_to_maven:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Publish package to Maven Repository
        run: ./gradlew publishToSonatype closeSonatypeStagingRepository
        env:
          SONATYPE_USER: ${{ secrets.SONATYPE_USER }}
          SONATYPE_KEY: ${{ secrets.SONATYPE_KEY }}
          SIGNING_KEY_ID: ${{ secrets.SIGNING_KEY_ID }}
          SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
          SIGNING_KEY_AMORED: ${{ secrets.SIGNING_KEY_AMORED }}
          # run: ./gradlew publishToSonatype closeAndReleaseSonatypeStagingRepository

  deploy_gh_pages:
    needs: [publish_to_maven]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build Javadoc
        run: ./gradlew javadoc

      - name: Copy Javadoc in new folder
        run: cp -r ./tus-android-client/build/docs/javadoc ../github-pages/javadoc

      - name: Commit changes
        uses: EndBug/add-and-commit@v7
        with:
          author_name: release script
          message: 'Update GH-Pages'
          add: "*"
          cwd: './github-pages/javadoc'
          branch: gh-pages
          push: true








